name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
            path: ~/.gradle/caches
            key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              gradle-${{ runner.os }}-

      - name: Set up Android SDK
        run: |
          if [ ! -d "$HOME/android-sdk" ]; then
            sudo apt-get install -y wget unzip
            wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
            unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk
          fi
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK with Gradle (Debugging)
        run: ./gradlew clean assembleRelease --stacktrace

      - name: List files in APK output directory
        run: |
                ls -al app/build/outputs/apk/

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
            name: test-results
            path: app/build/test-results/**/*.xml

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
            name: android-apk-${{ github.sha }}
            path: app/build/outputs/apk/release/*.apk

      - name: Check Java version
        run: java -version
