name: Test Upload Artifact

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a test file
        run: echo "Hello, world!" > test.txt

      - name: Upload test file
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: test.txt