name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        run: |
          # Install necessary packages to download SDK
          sudo apt-get install -y wget unzip

          # Download and extract the SDK tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk

          # Set the ANDROID_HOME and update PATH environment variables
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

          # Accept SDK licenses
          yes | sdkmanager --licenses

          # Install Android SDK components for API 34 and Build Tools
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

          # Install other necessary SDK components (optional but recommended)
          sdkmanager "extras;android;m2repository" "extras;google;m2repository"

      - name: Build APK
        run: ./gradlew clean assembleRelease

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/test-results/testDebugUnitTest/

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk-${{ github.sha }}
          path: app/release/*.apk
          allowEmptyArchive: true

      - name: Check Java version
        run: java -version
