name: Test Upload Artifact

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a test file
        run: echo "Hello, world!" > test.txt

      - name: Debug GitHub Actions Environment
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Temp: $RUNNER_TEMP"
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "GitHub Action Path: $GITHUB_ACTION_PATH"

      - name: Upload test file
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: test.txt