name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        run: |
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Build APK
        run: ./gradlew clean assembleRelease

      - name: Run Unit Tests
        run: ./gradlew test

      - name: List build output directory
        run: ls -R app/build/outputs/apk/debug/

      - name: Upload Debug APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk-debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/*.apk
          allowEmptyArchive: true

      - name: Check Java version
        run: java -version
